version: "2"
services:
  backend:
    container_name: backend
    restart: always
    build: ./back/
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/backend
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27107"
