version: "3"
services:
  frontend:
    container_name: frontend
    restart: always
    build: ./front/
    ports:
      - "80:80"
    environment:
      WAIT_HOSTS: mongo:27017 0.0.0.0:3000
    depends_on: [mongo, backend]
    links: [mongo, backend]
  backend:
    container_name: backend
    restart: always
    build: ./back/
    ports:
      - "3000:3000"
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on: [mongo]
    volumes:
      - ./back:/usr/src/backend
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27107"
